### PR TITLE
[BUGS-5608] Add extra check for source and destination to be site.env.

### LINKED ISSUE #35: PHP Fatal error:  Uncaught Error: Call to a member function get()
```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in ~/.terminus/terminus-dependencies-7422d8f8f1/vendor/pantheon-systems/terminus-site-clone-plugin/src/Commands/SiteCloneCommand.php:214
```

### PR DESCRIPTION
**Pull request by kporras07**
Closes #35 as it's adding an extra validation for the source and destination to be in the form <site>.<env>.

### CODE REVIEW

File: src/Commands/SiteCloneCommand.php [hunk 1]
```diff
@@ -72,6 +72,10 @@ public function clonePantheonSite(
             $this->options[$key] = boolval( $value );
         }
 
+        if (!preg_match('/.*\..*/', $user_source) || !preg_match('/.*\..*/', $user_destination)) {
```
Comment (namespacebrian) [inline src/Commands/SiteCloneCommand.php:75]: I think you want `.+`s here rather than `.*`s.. 

`*` matches "zero or more" so it will happily match an empty string.  `.` is a valid `site.env` with this regex as-is.
